name: 'Tests: node.js >= 22'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '^22.20 || ^24.10 || >= 25'
      type: minors
      command: npm run tests-only
